
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
=======
using System.Web;
>>>>>>> origin/develop

namespace SiliconShores.Models
{

using System;
    using System.Collections.Generic;
    
public partial class attraction
{

    public attraction()
    {
<<<<<<< HEAD

        this.breakdowns = new HashSet<breakdown>();

        this.daily_ride_report = new HashSet<daily_ride_report>();

=======
        public attraction()
        {
            this.breakdowns = new HashSet<breakdown>();
            this.daily_ride_report = new HashSet<daily_ride_report>();
        }
    
        public int attractions_id { get; set; }
        public string attraction_name { get; set; }
        public int theme_area_id { get; set; }
        public string attraction_description { get; set; }
        public string picture_path { get; set; }
        public bool is_working { get; set; }
        public System.DateTime date_opened { get; set; }
    
        public virtual ICollection<breakdown> breakdowns { get; set; }
        public virtual ICollection<daily_ride_report> daily_ride_report { get; set; }
        public virtual theme_areas theme_areas { get; set; }

        public String getImagePath()
        {
            return "/Content/Images" + theme_areas.theme_area_pictures + picture_path;
        }
>>>>>>> origin/develop
    }


    public int attractions_id { get; set; }

    public string attraction_name { get; set; }

    public int theme_area_id { get; set; }

    public string attraction_description { get; set; }

    public string picture_path { get; set; }

    public bool is_working { get; set; }

    public System.DateTime date_opened { get; set; }



    public virtual ICollection<breakdown> breakdowns { get; set; }

    public virtual ICollection<daily_ride_report> daily_ride_report { get; set; }

    public virtual theme_areas theme_areas { get; set; }

}

}
