//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconShores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class daily_weather
    {
        public System.DateTime weather_date { get; set; }
        public int theme_park_id { get; set; }
        public string weather_conditions { get; set; }
        public int high_temp { get; set; }
        public int low_temp { get; set; }
        public virtual theme_park theme_park { get; set; }
    }
}
