//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconShores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class food_categories
    {
        public food_categories()
        {
            this.restaurants = new HashSet<restaurant>();
        }

        public int food_category_id { get; set; }
        public string food_categories_name { get; set; }

        public virtual ICollection<restaurant> restaurants { get; set; }
    }
}
