//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconShores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_rides
    {
        public System.DateTime report_date { get; set; }
        public int attraction_id { get; set; }
        public int total_riders { get; set; }
        public string attraction_name { get; set; }
        public System.DateTime date_opened { get; set; }
    }
}
