//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconShores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class restaurant_daily_reports
    {
        public System.DateTime report_date { get; set; }
        public int restaurant_id { get; set; }
        public decimal gross_income { get; set; }
        public int patrons_served { get; set; }

        public virtual restaurant restaurant { get; set; }
    }
}
