//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;

namespace SiliconShores.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class theme_park_dbEntities : DbContext
    {
        public theme_park_dbEntities()
            : base("name=theme_park_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attraction> attractions { get; set; }
        public virtual DbSet<breakdown> breakdowns { get; set; }
        public virtual DbSet<daily_ride_report> daily_ride_report { get; set; }
        public virtual DbSet<daily_weather> daily_weather { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<food_categories> food_categories { get; set; }
        public virtual DbSet<hotel_reservations> hotel_reservations { get; set; }
        public virtual DbSet<hotel_rooms> hotel_rooms { get; set; }
        public virtual DbSet<hotel> hotels { get; set; }
        public virtual DbSet<restaurant_daily_reports> restaurant_daily_reports { get; set; }
        public virtual DbSet<restaurant> restaurants { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<room_types> room_types { get; set; }
        public virtual DbSet<theme_areas> theme_areas { get; set; }
        public virtual DbSet<theme_park> theme_park { get; set; }
        public virtual DbSet<ticket_sales> ticket_sales { get; set; }
        public virtual DbSet<ticket_types> ticket_types { get; set; }
        public virtual DbSet<userclaim> userclaims { get; set; }
        public virtual DbSet<userlogin> userlogins { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<report_restaurant> report_restaurant { get; set; }
        public virtual DbSet<report_rides> report_rides { get; set; }
        public virtual DbSet<report_ticketsales> report_ticketsales { get; set; }
    }
}
