//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiliconShores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ticket_types
    {
        public ticket_types()
        {
            this.ticket_sales = new HashSet<ticket_sales>();
        }
    
        [Required]
        [Display(Name = "Ticket Type ID")]
        public int ticket_type_id { get; set; }
        [Required]
        [Display(Name = "Ticket Name")]
        public string ticket_name { get; set; }
        [Required]
        [Display(Name = "Ticket Restrictions")]
        public string ticket_restrictions { get; set; }
        [Required]
        [Display(Name = "Ticket Price")]
        public Nullable<float> ticket_price { get; set; }
        [Required]
        [Display(Name = "Ticket Sales")]
        public virtual ICollection<ticket_sales> ticket_sales { get; set; }
    }
}
