
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SiliconShores.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ticket_sales
{

    public int ticket_id { get; set; }

    public int ticket_type_id { get; set; }

    public System.DateTime sale_date { get; set; }

    public Nullable<System.DateTime> redemption_date { get; set; }

    public int theme_park_id { get; set; }

    public string sale_location { get; set; }



    public virtual theme_park theme_park { get; set; }

    public virtual ticket_types ticket_types { get; set; }

}

}
